### ISSUE TITLE
Does this image depend on the host os version (libc, X11 version, ...)?

### ISSUE THREAD

**Issue by emmenlau** [thewtex/docker-opengl-nvidia#4]
I like the basic idea of this image and use it successfully on several Ubuntu machines.
However I could only get it to work with the same Ubuntu version. The reason may be
that I am using the graphics drivers ppa for the proprietary NVidia drivers, and not the
official driver download.
My question: is it supported to run a different Ubuntu version in the docker container
than in the host OS, as long as the NVidia driver is the exact same version? Or are
there other dependencies, like same libc version, same libstdc++ version, same X11
version, ...?

**Comment by thewtex** [comment]
I have successfully used Debian host with Ubuntu image for example. I would not expect that different versions of Ubuntu would have issues.

It would be interesting to know if using the official NVidia driver on your host addresses the issue.

**Comment by emmenlau** [comment]
Ok I will test this with the official NVidia driver and report back. Thanks!

**Comment by emmenlau** [comment]
I guess this can be closed now.
